// react-app/src/App.js
import { useEffect, useRef, useState } from 'react';
import './App.css';

function App() {
  // State
  const [todos, setTodos] = useState([]);

  // Binding
  const todoText = useRef();

  // Side Effects / Lifecycle
  useEffect(() => {
    const existingTodos = localStorage.getItem('todos');
    setTodos(existingTodos ? JSON.parse(existingTodos) : []);
  }, []);

  // Events
  function addTodo(event) {
    event.preventDefault();
    const next = [...todos, todoText.current.value];
    setTodos(next);
    localStorage.setItem('todos', JSON.stringify(next));
    todoText.current.value = ''; // Clear the todoText input after adding a todo
  }

  function clearList() {
    setTodos([]);
    localStorage.removeItem('todos');
  }

  return (
    <div>
      <ul>
        {todos.map((todo, index) => (
          <li key={index}>{todo}</li>
        ))}
      </ul>

      <form onSubmit={addTodo}>
        <input type="text" ref={todoText} />
        <input type="submit" value="Add Todo" />
        <button type="button" onClick={clearList}>Clear List</button>
      </form>
    </div>
  );
}

export default App;

// angular-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular-app';
  todos: string[] = [];
  todoText = '';

  ngOnInit() {
    const existingTodos = localStorage.getItem('todos');
    this.todos = JSON.parse(existingTodos as string) || [];
  }

  addTodo() {
    this.todos.push(this.todoText);
    localStorage.setItem('todos', JSON.stringify(this.todos));
  }

  // Add the clearList method
  clearList() {
    this.todos = [];
    localStorage.removeItem('todos');
  }
}
<div>
  <ul>
    <li *ngFor="let todo of todos">{{todo}}</li>
  </ul>

  <form (ngSubmit)="addTodo()">
    <input name="todotext" [(ngModel)]="todoText">
    <input type="submit" value="Add Todo">
    <button type="button" (click)="clearList()">Clear List</button>
  </form>
</div>
